/*
 * MiscItemDialog.java
 *
 * Created on December 10, 2006, 4:29 PM
 */

package businessmanager.InvoiceQuote;
import RuntimeManagement.GlobalApplicationDaemon;

import businessmanager.Common.JTextFieldFilter;
import businessmanager.Common.LimitedDocument;
import businessmanager.Common.VATCalculator;
import javax.swing.table.*;
import datavirtue.*;
import javax.swing.JOptionPane;
import java.util.ArrayList;

/**
 *
 * @author  Sean K Anderson - Data Virtue
 * @rights Copyright Data Virtue 2006, 2007, 2008 All Rights Reserved.
 */
public class MiscItemDialog extends javax.swing.JDialog {
    private GlobalApplicationDaemon application;
    private Settings props;
    /** Creates new form MiscItemDialog */
    public MiscItemDialog(java.awt.Frame parent, boolean modal, GlobalApplicationDaemon application, Object [] edit) {
        super(parent, modal);
        initComponents();
        java.awt.Dimension dim = DV.computeCenter((java.awt.Window) this);
        this.setLocation(dim.width, dim.height);
        this.application = application;

        db = application.getDb();
        props = application.getProps();

        unitField.setDocument(new JTextFieldFilter(JTextFieldFilter.FLOAT));
        /* Allow the price field to accept negative numbers */
        JTextFieldFilter tf = (JTextFieldFilter)unitField.getDocument();
        tf.setNegativeAccepted(true);

        costField.setDocument(new JTextFieldFilter(JTextFieldFilter.FLOAT));
        
        descField.setDocument(new LimitedDocument(50));
        longNoteBox.setDocument(new LimitedDocument(1000));
        
        this.populateItemList();
        
        tax1Box.setText(props.getProp("TAX1NAME"));
        tax2Box.setText(props.getProp("TAX2NAME"));
        
        if (edit != null) populate(edit);
        
        this.setVisible(true);
       
    }
    
    private void populate(Object [] edit){
        
        //45679
        //desc price tax1 tax2 cost
        descField.setText((String)edit[4]);
        unitField.setText(DV.money((Float)edit[5]));
        tax1Box.setSelected((Boolean)edit[6]);
        tax2Box.setSelected((Boolean)edit[7]);
        costField.setText(DV.money((Float)edit[9]));
        descField.requestFocus();
        
    }
    
    private java.util.ArrayList itemList;
    
    private void populateItemList () {
        
         itemList = new java.util.ArrayList();
        itemList.trimToSize();
        
        TableModel cat_tm = db.createTableModel("miscitems");
        
        if (cat_tm != null && cat_tm.getRowCount() > 0){
            
            for (int r = 0; r < cat_tm.getRowCount(); r++){
            
                itemList.add((String) cat_tm.getValueAt(r, 1));
                
            }
        
         
        }else {
            
            itemList.add("N/A");
        }
        
        descField.setDocument(new AutoCompleteDocument( descField, itemList ));
        
        
    }
    
    private void normalizeItemList(String s) {
        
        
        String txm;
        
        java.util.ArrayList al;
        
        al = db.search("miscitems", 1, s, false);
        
        if (al == null){
            
            db.saveRecord("miscitems",new Object [] {new Integer(0), new String (s)} ,false);
           
        }
        
        
    }
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        descField = new javax.swing.JTextField();
        tax1Box = new javax.swing.JCheckBox();
        tax2Box = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        itemNote = new javax.swing.JCheckBox();
        unitField = new javax.swing.JTextField();
        costField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        longNoteBox = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        VATButton = new javax.swing.JButton();
        addButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Non-Inventory Item");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        descField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        descField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                descFieldFocusGained(evt);
            }
        });

        tax1Box.setFont(new java.awt.Font("Tahoma", 0, 14));
        tax1Box.setText("Tax 1");
        tax1Box.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        tax1Box.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        tax1Box.setIconTextGap(2);

        tax2Box.setFont(new java.awt.Font("Tahoma", 0, 14));
        tax2Box.setText("Tax 2");
        tax2Box.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        tax2Box.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        tax2Box.setIconTextGap(2);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Description");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel3.setText("Price");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel5.setText("Cost");

        itemNote.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        itemNote.setText("Designate this invoice item as a \"note.\"");
        itemNote.setToolTipText("Prevents pricing or code information from displaying on the invoice.");
        itemNote.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        itemNote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemNoteActionPerformed(evt);
            }
        });

        unitField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        unitField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        unitField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                unitFieldFocusGained(evt);
            }
        });

        costField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        costField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        costField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                costFieldFocusGained(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Taxable");

        longNoteBox.setColumns(20);
        longNoteBox.setLineWrap(true);
        longNoteBox.setRows(5);
        longNoteBox.setWrapStyleWord(true);
        jScrollPane1.setViewportView(longNoteBox);

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 645, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel1Layout.createSequentialGroup()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(descField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 337, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 328, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(6, 6, 6)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                            .add(jLabel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(unitField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(tax1Box)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(tax2Box))
                            .add(jLabel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 96, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel5)
                            .add(costField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 75, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(org.jdesktop.layout.GroupLayout.LEADING, itemNote))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(17, 17, 17)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel3)
                    .add(jLabel2)
                    .add(jLabel5)
                    .add(jLabel4))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(descField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(tax1Box)
                    .add(unitField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(tax2Box)
                    .add(costField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(itemNote)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel1.setText("Enter the true cost to keep the COGS report valid.");

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        VATButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/businessmanager/res/Aha-16/enabled/Calculator.png"))); // NOI18N
        VATButton.setText("VAT");
        VATButton.setFocusable(false);
        VATButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        VATButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        VATButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VATButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(VATButton);

        addButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/businessmanager/res/Aha-16/enabled/Create.png"))); // NOI18N
        addButton.setText("Add Item");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(addButton);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(layout.createSequentialGroup()
                        .add(jLabel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 444, Short.MAX_VALUE)
                        .add(41, 41, 41)
                        .add(jToolBar1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 188, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jLabel1)
                    .add(jToolBar1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemNoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemNoteActionPerformed
        
        toggleItemNote();
        
        
    }//GEN-LAST:event_itemNoteActionPerformed

    
    private void toggleItemNote() {
        boolean sw;
        
        if (itemNote.isSelected()) sw = false;
        else sw = true;
        
        unitField.setText("0.00");
        unitField.setEnabled(sw);
        costField.setText("0.00");
        costField.setEnabled(sw);
        tax1Box.setSelected(false);
        tax2Box.setSelected(false);
        tax1Box.setEnabled(sw);
        tax2Box.setEnabled(sw);
        
    }
    
    
    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        //verify each field and bitch
        //format everything properly
        //convert all fields to their proper format
        //then assing new vals to miscItem
        ArrayList al;
        
        String desc = descField.getText().trim();
        
        
        /* check for duplicates in inventory*/
        
        al = db.searchFast("inventory", 3, desc, false );
        if (al != null){
            
            javax.swing.JOptionPane.showMessageDialog(null, "Duplicate description found in inventory, action canceled.");
            return;
        }
        
        
        String price = unitField.getText().trim();
        String cost = costField.getText().trim();
        
        
        if (DV.validFloatString(price)); 
        else {JOptionPane.showMessageDialog(this, "Please enter a valid Unit Price: '0.00' numbers and decimal only.", price,  JOptionPane.OK_OPTION); return;}
        
        if (DV.validFloatString(cost)); 
        else {JOptionPane.showMessageDialog(this, "Please enter a valid Cost Price: '0.00' numbers and decimal only.", cost,  JOptionPane.OK_OPTION); return;}
        
        if (desc.equals("") || desc.length() < 5 || desc.length() > 50){
            
          JOptionPane.showMessageDialog(this, "Please enter a good Description, up to 50 characters.", "Important Field",  JOptionPane.OK_OPTION);
          return;
        }
        
        al = db.search("inventory", 3, desc, false );
        
        if (al == null);
        else {
            
          JOptionPane.showMessageDialog(this, "The Description you provided was found in Inventory." + nl +
                  " Please use another.", "Invalid Description",  JOptionPane.OK_OPTION);
          
          descField.requestFocus();
          descField.selectAll();
          
          return;
            
        }
        
        float unit  = 0.00f;
        float costf = 0.00f;
        costf = Float.parseFloat(cost);
        unit = Float.parseFloat(price);
        
        miscItem [2] = "MISC";  //code
        
        String note = desc;
        //if (!itemNote.isSelected()) note = desc.toUpperCase().trim();
        
        miscItem [3] = note;  //desc
        miscItem [7] = new Float (costf);  //cost
        miscItem [8] = new Float (unit);  //unit
        miscItem [13] = tax1Box.isSelected();  //t1
        miscItem [14] = tax2Box.isSelected();  //t2
        itemLongNote = longNoteBox.getText();
        
        stat = true;
        
        this.normalizeItemList(descField.getText());        
        this.VATButton.setVisible(DV.parseBool(application.getProps().getProp("VAT"), true));
        this.setVisible(false);
    }//GEN-LAST:event_addButtonActionPerformed

    private void unitFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_unitFieldFocusGained
        unitField.selectAll();
    }//GEN-LAST:event_unitFieldFocusGained

    private void costFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_costFieldFocusGained
        costField.selectAll();
    }//GEN-LAST:event_costFieldFocusGained

    private void descFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_descFieldFocusGained
        descField.selectAll();
    }//GEN-LAST:event_descFieldFocusGained

    private void VATButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VATButtonActionPerformed
        new VATCalculator(null, true, DV.parseFloat(props.getProp("TAX1")));
    }//GEN-LAST:event_VATButtonActionPerformed
    
    public boolean getStat() {
        
        return stat;
        
    }
    
    public Object [] getItem () {
        
        return miscItem;
        
    }
    
    public String getLongNote(){
        return itemLongNote;
    }
    private Object [] miscItem = new Object [16];  //the size of an inventory record
    private boolean stat = false;
    private DbEngine db;
    private String nl = System.getProperty("line.separator");
    private String itemLongNote = "";
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton VATButton;
    private javax.swing.JButton addButton;
    private javax.swing.JTextField costField;
    private javax.swing.JTextField descField;
    private javax.swing.JCheckBox itemNote;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTextArea longNoteBox;
    private javax.swing.JCheckBox tax1Box;
    private javax.swing.JCheckBox tax2Box;
    private javax.swing.JTextField unitField;
    // End of variables declaration//GEN-END:variables
    
}
